// Loadable modules
//
// Generated by /root/src/ParaView-bin/bin/vtkkwProcessXML-pv4.2
//
#ifndef __vtkSMXML_vtkBumpMapper_h
#define __vtkSMXML_vtkBumpMapper_h

#include <string.h>


// From file /import/etud/43/sberger/Bureau/visualisation/paraview/BumpMapper/vtkBumpMapper.xml
static const char* const vtkBumpMappervtkBumpMapperInterfaces0 =
"    <ServerManagerConfiguration>\n"
"      <ProxyGroup name=\"filters\">\n"
"        <SourceProxy name=\"vtkBumpMapper\" class=\"vtkBumpMapper\" label=\"Bump Mapper\">\n"
"        <Documentation long_help=\"This filter generates an arrow, cone, cube, cylinder, line, sphere, or 2D glyph at each point of the input data set.  The glyphs can be oriented and scaled by point attributes of the input dataset.\" short_help=\"Generate a glyph symbol at each point of the input data set.\">\n"
"            The Glyph filter generates a glyph (i.e., an arrow, cone, cube, cylinder, line, sphere, or 2D glyph) at each point in the input dataset. The glyphs can be oriented and scaled by the input point-centered scalars and vectors. The Glyph filter operates on any type of data set. Its output is polygonal. This filter is available on the Toolbar.\n"
"        </Documentation>\n"
"\n"
"        <InputProperty\n"
"            name=\"LineDataSet\"\n"
"            command=\"SetInputConnection\">\n"
"            <ProxyGroupDomain name=\"groups\">\n"
"                <Group name=\"sources\"/>\n"
"                <Group name=\"filters\"/>\n"
"            </ProxyGroupDomain>\n"
"            <DataTypeDomain name=\"input_type\">\n"
"                <DataType value=\"vtkPolyData\"/>\n"
"            </DataTypeDomain>\n"
"            <Documentation>\n"
"                Set the source data set landmark points.\n"
"            </Documentation>\n"
"        </InputProperty>\n"
"\n"
"        <DoubleVectorProperty\n"
"        name=\"CurrentIntegrationTime\"\n"
"        label=\"Current Step\"\n"
"        command=\"SetCurrentIntegrationTime\"\n"
"        number_of_elements=\"1\"\n"
"        default_values=\"0.0\">\n"
"        <DoubleRangeDomain name=\"range\"/>\n"
"        </DoubleVectorProperty>\n"
"\n"
"        <Hints>\n"
"        <!-- Visibility Element can be used to suggest the GUI about\n"
"        visibility of this filter (or its input) on creation.\n"
"        replace_input=\"0\" implies that the input visibility is not\n"
"        changed on creation of this filter (defaults to \"1\")\n"
"        -->\n"
"            <Visibility replace_input=\"1\" />\n"
"        </Hints>\n"
"        <!-- End Glyph -->\n"
"        </SourceProxy>\n"
"      </ProxyGroup>\n"
"    </ServerManagerConfiguration>\n"
"\n";
// Get single string
char* vtkBumpMappervtkBumpMapperInterfaces()
{
  size_t len = ( 0
    + strlen(vtkBumpMappervtkBumpMapperInterfaces0) );
  char* res = new char[ len + 1];
  res[0] = 0;
  strcat(res, vtkBumpMappervtkBumpMapperInterfaces0);
  return res;
}



#endif
